{"url": "https://api.github.com/repos/datalad/datalad/issues/6026", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/6026/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/6026/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/6026/events", "html_url": "https://github.com/datalad/datalad/issues/6026", "id": 1013983336, "node_id": "I_kwDOANZqws48cCho", "number": 6026, "title": "Lots of `server certificate verification failed. CAfile: none CRLfile` errors on ubuntu CI", "user": {"login": "mih", "id": 136479, "node_id": "MDQ6VXNlcjEzNjQ3OQ==", "avatar_url": "https://avatars.githubusercontent.com/u/136479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mih", "html_url": "https://github.com/mih", "followers_url": "https://api.github.com/users/mih/followers", "following_url": "https://api.github.com/users/mih/following{/other_user}", "gists_url": "https://api.github.com/users/mih/gists{/gist_id}", "starred_url": "https://api.github.com/users/mih/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mih/subscriptions", "organizations_url": "https://api.github.com/users/mih/orgs", "repos_url": "https://api.github.com/users/mih/repos", "events_url": "https://api.github.com/users/mih/events{/privacy}", "received_events_url": "https://api.github.com/users/mih/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2021-10-02T08:55:03Z", "updated_at": "2021-10-03T16:58:09Z", "closed_at": "2021-10-03T16:58:09Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "Sample https://ci.appveyor.com/project/mih/datalad/build/job/begrlqetcsw4f3ra\r\n\r\nSeems unspecific to this PR.\r\n\r\nReported for\r\n\r\n- https://datasets-tests.datalad.org\r\n- https://gin.g-node.org\r\n\r\nand possibly CRCNS.org, but hidden in a more complex download failure.\r\n\r\nGiven that it is only the linux workers, and that it is not a single host for which it fails, I blame the certificate setup in the worker.", "closed_by": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/6026/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/6026/timeline", "performed_via_github_app": null}