{"url": "https://api.github.com/repos/datalad/datalad/issues/1099", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/1099/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/1099/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/1099/events", "html_url": "https://github.com/datalad/datalad/issues/1099", "id": 187901433, "node_id": "MDU6SXNzdWUxODc5MDE0MzM=", "number": 1099, "title": "publish claims that sibling doesn't exist.  should report under which repo", "user": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2016-11-08T04:50:24Z", "updated_at": "2016-11-25T19:56:47Z", "closed_at": "2016-11-25T19:56:47Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "```shell\r\n(git)smaug:/mnt/datasets/datalad/crawl[master]git\r\n$> datalad publish -r --to datalad-public\r\n[ERROR  ] No sibling 'datalad-public' found. [publish.py:__call__:289] (ValueError) \r\n(venv-tests)1 10221 ->1.....................................:Mon 07 Nov 2016 11:45:48 PM EST:.\r\n(git)smaug:/mnt/datasets/datalad/crawl[master]git\r\n$> git remote                            \r\ndatalad-dev-public\r\ndatalad-public\r\nchanges on filesystem:                                                                                          \r\n crcns      | 2 +-\r\n dicoms     | 2 +-\r\n indi       | 2 +-\r\n kaggle     | 2 +-\r\n labs       | 2 +-\r\n neurovault | 2 +-\r\n nidm       | 2 +-\r\n```\r\ntried with both current master  and #1037.. and then realized that it is probably due to some burried down dataset... indeed it was due to some dataset underneath... so at least error msg should say for which dataset this remote doesn't exist.\r\n\r\nhopefully tomorrow I will brush up the current state of our collection and get it published -- all openfmri datasets are ready ", "closed_by": {"login": "mih", "id": 136479, "node_id": "MDQ6VXNlcjEzNjQ3OQ==", "avatar_url": "https://avatars.githubusercontent.com/u/136479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mih", "html_url": "https://github.com/mih", "followers_url": "https://api.github.com/users/mih/followers", "following_url": "https://api.github.com/users/mih/following{/other_user}", "gists_url": "https://api.github.com/users/mih/gists{/gist_id}", "starred_url": "https://api.github.com/users/mih/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mih/subscriptions", "organizations_url": "https://api.github.com/users/mih/orgs", "repos_url": "https://api.github.com/users/mih/repos", "events_url": "https://api.github.com/users/mih/events{/privacy}", "received_events_url": "https://api.github.com/users/mih/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/1099/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/1099/timeline", "performed_via_github_app": null}