{"url": "https://api.github.com/repos/datalad/datalad/issues/4363", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/4363/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/4363/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/4363/events", "html_url": "https://github.com/datalad/datalad/issues/4363", "id": 591250611, "node_id": "MDU6SXNzdWU1OTEyNTA2MTE=", "number": 4363, "title": "dataset.config fails to detect changed config file (seems to be master specific)", "user": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 9, "created_at": "2020-03-31T16:34:10Z", "updated_at": "2020-04-01T14:41:07Z", "closed_at": null, "author_association": "MEMBER", "active_lock_reason": null, "body": "Origin: https://github.com/datalad/datalad-extensions/pull/7#issuecomment-606725942\r\n```\r\n(git)lena:~datalad/datalad-master[master]git\r\n$> python -m nose -s -v datalad/metadata/tests/test_base.py:test_get_metadata_type\r\ndatalad.metadata.tests.test_base.test_get_metadata_type ... HERE0\r\nHERE1:  /home/yoh/.tmp/datalad_temp_test_get_metadata_typet6b5ptfh\r\nFAIL\r\nVersions: appdirs=1.4.3 boto=2.49.0 cmd:7z=16.02 cmd:annex=7.20190819+git2-g908476a9b-1~ndall+1 cmd:bundled-git=2.20.1 cmd:git=2.20.1 cmd:system-git=2.25.1 cmd:system-ssh=8.1p1 exifread=2.1.2 git=3.0.7 gitdb=2.0.6 humanize=0.5.1 iso8601=0.1.12 keyring=18.0.1 keyrings.alt=3.2.0 msgpack=0.5.6 mutagen=1.40.0 requests=2.22.0 tqdm=4.30.0 wrapt=1.11.2\r\nObscure filename: str=b' \"\\';a&b&c\\xce\\x94\\xd0\\x99\\xd7\\xa7\\xd9\\x85\\xe0\\xb9\\x97\\xe3\\x81\\x82 `| ' repr=' \"\\';a&b&c\u0394\u0419\u05e7\u0645\u0e57\u3042 `| '\r\nEncodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'\r\nEnvironment: PATH='/home/yoh/proj/datalad/datalad-master/venvs/dev3/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin' LANG='en_US.UTF-8' GIT_PAGER='less --no-init --quit-if-one-screen' GIT_PYTHON_GIT_EXECUTABLE='/usr/lib/git-annex.linux/git'\r\n\r\n======================================================================\r\nFAIL: datalad.metadata.tests.test_base.test_get_metadata_type\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/usr/lib/python3/dist-packages/nose/case.py\", line 197, in runTest\r\n    self.test(*self.arg)\r\n  File \"/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py\", line 691, in newfunc\r\n    return t(*(arg + (filename,)), **kw)\r\n  File \"/home/yoh/proj/datalad/datalad-master/datalad/metadata/tests/test_base.py\", line 92, in test_get_metadata_type\r\n    assert_equal(get_metadata_type(ds), 'mamboschwambo')\r\nAssertionError: [] != 'mamboschwambo'\r\n```\r\n\r\nHappens in `test_get_metadata_type` where  we append explicitly to `.datalad/config` file,\r\n\r\nIt actually seems to be not git/git-annex version specific -- happens with our stock neurodebian git annex 7.20190819+git2-g908476a9b-1~ndall+1, not sure how was not spotted...\r\n\r\nsomehow does not happen on maint - there config seems to be nicely reread... I have not spotted any relevant diff in `datalad/metadata/tests/test_base.py` or `datalad/config.py`...\r\n\r\nMay be some recent changes give ideas @kyleam @mih ? before we try to bisect or figure it out otherwise", "closed_by": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/4363/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/4363/timeline", "performed_via_github_app": null}