{"url": "https://api.github.com/repos/datalad/datalad/issues/5729", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/5729/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/5729/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/5729/events", "html_url": "https://github.com/datalad/datalad/issues/5729", "id": 917115913, "node_id": "MDU6SXNzdWU5MTcxMTU5MTM=", "number": 5729, "title": "Debian package dependency issue with python3-github", "user": {"login": "mih", "id": 136479, "node_id": "MDQ6VXNlcjEzNjQ3OQ==", "avatar_url": "https://avatars.githubusercontent.com/u/136479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mih", "html_url": "https://github.com/mih", "followers_url": "https://api.github.com/users/mih/followers", "following_url": "https://api.github.com/users/mih/following{/other_user}", "gists_url": "https://api.github.com/users/mih/gists{/gist_id}", "starred_url": "https://api.github.com/users/mih/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mih/subscriptions", "organizations_url": "https://api.github.com/users/mih/orgs", "repos_url": "https://api.github.com/users/mih/repos", "events_url": "https://api.github.com/users/mih/events{/privacy}", "received_events_url": "https://api.github.com/users/mih/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 390153891, "node_id": "MDU6TGFiZWwzOTAxNTM4OTE=", "url": "https://api.github.com/repos/datalad/datalad/labels/UX", "name": "UX", "color": "0052cc", "default": false, "description": "user experience"}, {"id": 1056431670, "node_id": "MDU6TGFiZWwxMDU2NDMxNjcw", "url": "https://api.github.com/repos/datalad/datalad/labels/debian-packaging", "name": "debian-packaging", "color": "0052cc", "default": false, "description": "Issues of Debian packaging/integration"}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2021-06-10T09:19:27Z", "updated_at": "2021-07-23T08:43:36Z", "closed_at": "2021-07-23T08:43:36Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "`python3-github` is recommended by `python3-datalad` and is installed on this Debian buster machine:\r\n\r\n```\r\n% apt-cache policy python3-github\r\npython3-github:\r\n  Installed: 1.43.7-1~nd100+1\r\n  Candidate: 1.43.7-1~nd100+1\r\n  Version table:\r\n *** 1.43.7-1~nd100+1 500\r\n        500 http://neurodebian.mirror.htc.inm7.de/debian buster/main amd64 Packages\r\n        100 /var/lib/dpkg/status\r\n     1.40-1 500\r\n        500 http://debian.mirror.htc.inm7.de/debian buster/main amd64 Packages\r\n```\r\n\r\nbut it is not functional\r\n\r\n```\r\nmih@juseless ~ % python3 -c \"import github\"\r\nTraceback (most recent call last):\r\n  File \"<string>\", line 1, in <module>\r\n  File \"/usr/lib/python3/dist-packages/github/__init__.py\", line 42, in <module>\r\n    from github.MainClass import Github, GithubIntegration\r\n  File \"/usr/lib/python3/dist-packages/github/MainClass.py\", line 74, in <module>\r\n    from . import RateLimit\r\n  File \"/usr/lib/python3/dist-packages/github/RateLimit.py\", line 33, in <module>\r\n    from deprecated import deprecated\r\nModuleNotFoundError: No module named 'deprecated'\r\n```\r\n\r\nand this leads to\r\n\r\n```\r\n% datalad create-sibling-github some\r\n[ERROR  ] PyGitHub is missing. GitHub-related functionality is unavailable without this package [github_.py:<module>:35] (MissingExternalDependency) \r\n```\r\n\r\nwhich is an invalid interpretation of the situation.\r\n\r\nInstalling `python3-deprecated` manually resolves the issue.\r\n\r\nI have not yet filed a bug against the `python3-github` Debian package, because this is a NeuroDebian backport, and may just be our bug.", "closed_by": {"login": "mih", "id": 136479, "node_id": "MDQ6VXNlcjEzNjQ3OQ==", "avatar_url": "https://avatars.githubusercontent.com/u/136479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mih", "html_url": "https://github.com/mih", "followers_url": "https://api.github.com/users/mih/followers", "following_url": "https://api.github.com/users/mih/following{/other_user}", "gists_url": "https://api.github.com/users/mih/gists{/gist_id}", "starred_url": "https://api.github.com/users/mih/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mih/subscriptions", "organizations_url": "https://api.github.com/users/mih/orgs", "repos_url": "https://api.github.com/users/mih/repos", "events_url": "https://api.github.com/users/mih/events{/privacy}", "received_events_url": "https://api.github.com/users/mih/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/5729/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/5729/timeline", "performed_via_github_app": null}