{"url": "https://api.github.com/repos/datalad/datalad/issues/5973", "repository_url": "https://api.github.com/repos/datalad/datalad", "labels_url": "https://api.github.com/repos/datalad/datalad/issues/5973/labels{/name}", "comments_url": "https://api.github.com/repos/datalad/datalad/issues/5973/comments", "events_url": "https://api.github.com/repos/datalad/datalad/issues/5973/events", "html_url": "https://github.com/datalad/datalad/issues/5973", "id": 993404399, "node_id": "MDU6SXNzdWU5OTM0MDQzOTk=", "number": 5973, "title": "test_download_url_need_datalad_remote: flaky?", "user": {"login": "yarikoptic", "id": 39889, "node_id": "MDQ6VXNlcjM5ODg5", "avatar_url": "https://avatars.githubusercontent.com/u/39889?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yarikoptic", "html_url": "https://github.com/yarikoptic", "followers_url": "https://api.github.com/users/yarikoptic/followers", "following_url": "https://api.github.com/users/yarikoptic/following{/other_user}", "gists_url": "https://api.github.com/users/yarikoptic/gists{/gist_id}", "starred_url": "https://api.github.com/users/yarikoptic/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yarikoptic/subscriptions", "organizations_url": "https://api.github.com/users/yarikoptic/orgs", "repos_url": "https://api.github.com/users/yarikoptic/repos", "events_url": "https://api.github.com/users/yarikoptic/events{/privacy}", "received_events_url": "https://api.github.com/users/yarikoptic/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2021-09-10T16:40:21Z", "updated_at": "2021-09-10T16:40:21Z", "closed_at": null, "author_association": "MEMBER", "active_lock_reason": null, "body": "was reported on happen on maint build on travis with the settings (not sure if matter): `_DL_TMPDIR=\"/var/tmp/sym link\" NOSE_SELECTION_OP=\"\" DATALAD_TESTS_OBSCURE_PREFIX=- DATALAD_LOG_TRACEBACK=collide`\r\n\r\nhttps://app.travis-ci.com/github/datalad/datalad/jobs/536670774\r\n\r\n```\r\n======================================================================\r\nERROR: datalad.interface.tests.test_download_url.test_download_url_need_datalad_remote\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/tmp/dl-miniconda-a8svhy90/lib/python3.9/site-packages/nose/case.py\", line 198, in runTest\r\n    self.test(*self.arg)\r\n  File \"/tmp/dl-miniconda-a8svhy90/lib/python3.9/site-packages/datalad/tests/utils.py\", line 190, in _wrap_skip_if_no_network\r\n    return func(*args, **kwargs)\r\n  File \"/tmp/dl-miniconda-a8svhy90/lib/python3.9/site-packages/datalad/tests/utils.py\", line 767, in _wrap_with_tempfile\r\n    return t(*(arg + (filename,)), **kw)\r\n  File \"/tmp/dl-miniconda-a8svhy90/lib/python3.9/site-packages/datalad/interface/tests/test_download_url.py\", line 243, in test_download_url_need_datalad_remote\r\n    ds_b.get(\"foo\")\r\n  File \"/tmp/dl-miniconda-a8svhy90/lib/python3.9/site-packages/datalad/distribution/dataset.py\", line 503, in apply_func\r\n    return f(**kwargs)\r\n  File \"/tmp/dl-miniconda-a8svhy90/lib/python3.9/site-packages/datalad/interface/utils.py\", line 481, in eval_func\r\n    return return_func(generator_func)(*args, **kwargs)\r\n  File \"/tmp/dl-miniconda-a8svhy90/lib/python3.9/site-packages/datalad/interface/utils.py\", line 474, in return_func\r\n    results = list(results)\r\n  File \"/tmp/dl-miniconda-a8svhy90/lib/python3.9/site-packages/datalad/interface/utils.py\", line 459, in generator_func\r\n    raise IncompleteResultsError(\r\ndatalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:\r\n[{'action': 'get',\r\n  'annexkey': 'MD5E-s4008--ef4867d3c21a0034a98cd9453f14efe3',\r\n  'message': 'not available',\r\n  'path': '/tmp/datalad_temp_test_download_url_need_datalad_remoteggc61t1u/b/foo',\r\n  'refds': '/tmp/datalad_temp_test_download_url_need_datalad_remoteggc61t1u/b',\r\n  'status': 'error',\r\n  'type': 'file'}]\r\n```", "closed_by": null, "reactions": {"url": "https://api.github.com/repos/datalad/datalad/issues/5973/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/datalad/datalad/issues/5973/timeline", "performed_via_github_app": null}